import os
Import( '*' )

# environment
env.VariantDir(
	build_dir,
	'#',
	duplicate = 0
)
slre = env.Clone()

# sources
files = [
	'slre/slre.c',
]
files = [build_dir + f for f in files]

# project settings
if realcc == 'gcc' or realcc == 'clang':
	if plat != 'Windows':
		slre['CCFLAGS'] += [
			'-fPIC',
		]
	slre['CFLAGS'] += [
		'-std=c99',
	]
	slre['CPPPATH'] += [
	'#' + os.sep + 'slre'
]
# targets
result = slre.StaticLibrary(
	build_dir + 'libslre',
	files
)
Return( "result" )
