language: c
compiler: gcc

install:
  - sudo apt-get install libreadline-dev

script:
  - scons -Q project=game debug=0 force32=0
  - scons -Q project=cgame debug=0 force32=0
  - scons -Q project=ui debug=0 force32=0
