env: MORE_WARNINGS=1

matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
      osx_image: xcode7.3

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libreadline-dev

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons sdl2; fi

script:
  - scons -Q -j1 debug=0 force32=0 no_sql=1
