language: cpp
compiler: g++
env: MORE_WARNINGS=1 CC= CXX=

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi

install:
  - sudo apt-get install libreadline-dev

script:
  - unset CC
  - unset CXX
  - scons -Q -j1 debug=0 force32=0 no_sql=1 CC=gcc-4.8 CXX=g++-4.8
